### PR TITLE
Fixes to work on GNU/Linux systems with cdrecord/cdirip + sundry cleanup

### PR DESCRIPTION
**Pull request by hackerb9**
* cdib no longer is hardcoded to only use the versions of cdrecord and cdirip that are included in this package. 
* cleanup logic surrounding $OS -eq "Darwin"
* Usage error message
* README is now in Markdown
* Use mktemp instead of creating the temp file in $HOME
* Quit as soon any unexpected error occurs

### CODE REVIEW

**Comment by alex-free** [comment]
Great work! I would like 2 things to be done before this is merged:
1) Remove build_select folder (it is no longer used in the Mac OS X build).
2) Fix the typo 'cdrecorder' (it should be cdrecord, which is provided by the cdrtools software suite).

Also IIRC darwin requires root because we need to unload a launch daemon on some newer Mac OS versions to get this to work right.

**Comment by hackerb9** [comment]
> Great work! I would like 2 things to be done before this is merged:
> 
>     1. Remove build_select folder (it is no longer used in the Mac OS X build).
> 
>     2. Fix the typo 'cdrecorder' (it should be cdrecord, which is provided by the cdrtools software suite).

Done.

> 
> Also IIRC darwin requires root because we need to unload a launch daemon on some newer Mac OS versions to get this to work right.

Hmm... perhaps the script should try first without root and only use `sudo` for the commands that require it. Is the only way to determine what permissions launchctl needs, is to just try and fail? 

At one point I was considering adding a check to make sure `cdrecord -inq` works and then printing some diagnostic information if it failed. Something like this:

```bash

if ! cdrecord $device -inq >/dev/null 2>&1; then
    echo "Error: cdrecord could not open your CD-R drive" >&2
    if [[ -e /dev/cdrom && ! -w /dev/cdrom ]]; then
	ls -lL /dev/cdrom
	perm=$(stat -L -c %a /dev/cdrom || true) # Permissions in octal (e.g., "660")
	perm=${perm: 1: 1}			 # Group permissions
	if (( $perm & 2 )); then		 # Is it group writeable?
	    g=$(stat -L -c %G /dev/cdrom || true)	# Get group owner name
	    if [[ $g != "root" ]]; then
		echo "Considering adding ${USER:-your account} to the ${g:-appropriate} group." >&2
	    fi
	fi
    fi
    exit 1
fi
```

I left it out because it is unlikely to be necessary on current GNU/Linux systems and my initial code for getting the group owner of /dev/cdrom is ~~barfy~~baroque. But, on the Mac, it sounds like the only solution is `sudo`, so maybe something like this would work:

```bash
if cdrecord $device -inq >/dev/null 2>&1; then
    maybesudo=""
else
    echo "cdrecord could not open your CD-R drive, trying again using sudo" >&2
    if ! sudo cdrecord $device -inq >/dev/null 2>&1; then
        echo "Error: could not access CD-R drive even as root." >&2
        exit 1
    else
        maybesudo=sudo
    fi
fi
⋮
$maybesudo cdrecord …
```

**Comment by alex-free** [comment]
launchctl 100% requires sudo to unload that launch daemon which breaks the script if it is not unloaded (it won't have access to burn the CD because the drive is "busy"). For Mac OS X it just is how it is, there is no way around that hacky behavior. 

I think this is fine as is. We don't need root on Mac OS X to actually burn the CD with cdrecord, just to unload the daemon (which has to be done multiple times as the OS is constantly trying to mount the partially burned CD-R). 

Remove the comment under the root check for mac os x saying is root really required in cdib and I'll merge this.

I am interested in packaging this up for Linux BTW. If you figure out a nice way that is actually portable let me know and I'll merge that as well.

**Comment by hackerb9** [comment]
Okay, I removed the comment.

> launchctl 100% requires sudo to unload that launch daemon which breaks the script if it is not unloaded (it won't have access to burn the CD because the drive is "busy"). For Mac OS X it just is how it is, there is no way around that hacky behavior.

Yuck, but I guess there's nothing that can be done.

> I think this is fine as is. We don't need root on Mac OS X to actually burn the CD with cdrecord, just to unload the daemon (which has to be done multiple times as the OS is constantly trying to mount the partially burned CD-R).

Why not use `sudo launchctl` inside the cdib? That way the rest of the script won't run as root and will be less dangerous. Sudo remembers authentication for a short period (≅15 minutes), so folks might have to type their passwords twice, but not every time unmount_cd() is run.

Also: I don't know MacOS, but the man page for launchctl implies that `unload` is an old, deprecated subcommand. It seems like `launchctl disable` may be the replacement, but I am not sure. Is it possible using disable might keep the Disk Arbitration daemon from coming back automatically?

If `disable` does work to keep it from automatically loading, I think you'll want to add `launchctl enable` in the cleanup() function so that the daemon will be sure to restart, even if cdib dies with an error or is killed by a signal.

**Pull request merged**
